language: node_js
  - node
sudo: required
services:
  - docker

before-install:
  - docker build -t ducnguyen095456/docker-react -f Dockerfile.dev . # chay file dockerfile.dev vs cai tag name phuocduc/docker-react

script:
  - docker run -e CI=true ducnguyen095456/docker-react npm run test -- --coverage # run test

deploy:
  provider: elasticbeanstalk #tên nha cung cap elasticbeantalk
  region: "ap-southeast-1" # trong phan url app nó là phần đứng trước elasticbeanstalk.com
  app: "react-docker" # app name
  env: "ReactDocker-env-1" # moi truong su dung
  bucket_name: "elasticbeanstalk-ap-southeast-1-406584201417" # trong service s3 của aws kiếm bucket moi tạo
  bucket_path: "react-docker" # mặc định khi chưa tạo thì lấy default thằng app name của application
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secrect_access_key:
    secure: "$AWS_SECRECT_KEY"
