language: node_js
node_js:
  - 12
sudo: required
services:
  - docker

before-install:
  - docker build -t ducnguyen095456/dockerreact -f Dockerfile.dev . # chay file dockerfile.dev vs cai tag name phuocduc/docker-react

script:
  - docker run -it -e CI=true ducnguyen095456/dockerreact npm run test -- --coverage # run test
